# Generated by Django 5.2 on 2025-04-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_token',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
